name: openfoamAgent
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - expat=2.6.4
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libuuid=1.41.5
  - libzlib=1.2.13
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.12.9
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.46.0
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.45.2
      - anyio==4.8.0
      - attrs==25.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - distro==1.9.0
      - faiss-cpu==1.10.0
      - frozenlist==1.5.0
      - gitingest==0.1.2
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - idna==3.10
      - jiter==0.8.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.18
      - langchain-anthropic==0.2.4
      - langchain-community==0.3.17
      - langchain-core==0.3.34
      - langchain-experimental==0.3.4
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.6
      - langgraph==0.2.71
      - langgraph-checkpoint==2.0.12
      - langgraph-sdk==0.1.51
      - langserve==0.3.1
      - langsmith==0.3.8
      - marshmallow==3.26.1
      - msgpack==1.1.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - numpy==2.2.2
      - openai==1.61.1
      - orjson==3.10.15
      - packaging==24.2
      - propcache==0.2.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - tenacity==9.0.0
      - tiktoken==0.8.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - urllib3==2.3.0
      - yarl==1.18.3
      - zstandard==0.23.0
      - boto3==1.36.26
      - langchain_aws==0.2.13
